name: Code coverage report
on:
  pull_request:
  push:
    branches:
      - main
      - rel-v*

env:
  CARGO_TERM_COLOR: always

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        name: Setup toolchain
        with:
          toolchain: nightly
          components: llvm-tools-preview

      - uses: Swatinem/rust-cache@v2

      - name: Setup coverage tool
        run: |
          mkdir grcov
          curl -sL https://github.com/mozilla/grcov/releases/latest/download/grcov-x86_64-unknown-linux-gnu.tar.bz2 | (cd grcov ; tar jxf -)

      - name: Stop SSH service
        run: sudo systemctl stop ssh

      - name: Test
        env:
          CI: true
          RUSTFLAGS: -Cinstrument-coverage
          LLVM_PROFILE_FILE: test-containers-%p-%m.profraw
          RUST_LOG: debug
        run: cargo test --all -- --include-ignored --nocapture

      - name: Fix target folder permissions
        run: |
          u=$(id -u)
          g=$(id -g)
          sudo chown -R $u:$g target/debug/

      - name: Generate coverage
        run: |
          grcov/grcov $(find . -name "test-containers-*.profraw" -print) \
            --branch \
            --ignore-not-existing \
            --binary-path ./target/debug/ \
            -s src \
            -t lcov \
            --ignore "/*" \
            --excl-line '^\s*\.await\??;?$' --excl-br-line '^\s*\.await\??;?$' \
            -o lcov.info

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          file: ./lcov.info
